import * as THREE from 'three';
export function mountNetwork(host:HTMLElement){
 const canvas=host.querySelector('canvas')!,stage=host.querySelector<HTMLElement>('.network-stage')!,status=host.querySelector<HTMLElement>('[data-scene-status]')!;
 const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:innerWidth>700,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.25:1.6));
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,3.9,9);camera.lookAt(0,0,0);
 scene.add(new THREE.AmbientLight(0xb2d6d0,1.8));const light=new THREE.DirectionalLight(0x8fffcf,3);light.position.set(-3,6,5);scene.add(light);const violet=new THREE.PointLight(0xa69af5,20,14);violet.position.set(4,3,1);scene.add(violet);
 const world=new THREE.Group();scene.add(world);const positions=[new THREE.Vector3(.3,.45,-1.6),new THREE.Vector3(-2.5,0,.75),new THREE.Vector3(.25,0,2),new THREE.Vector3(2.6,.25,-.1),new THREE.Vector3(-2.4,.15,-2)];
 const materials:THREE.Material[]=[],geometries:THREE.BufferGeometry[]=[];const mat=(color:number,metalness=.5)=>{const m=new THREE.MeshStandardMaterial({color,metalness,roughness:.35});materials.push(m);return m};const dark=mat(0x203c39),mint=mat(0x70ecc0),purple=mat(0xb0a0eb);
 const mesh=(geometry:THREE.BufferGeometry,material:THREE.Material)=>{geometries.push(geometry);return new THREE.Mesh(geometry,material)};
 const nodes=positions.map((p,i)=>{const group=new THREE.Group();group.position.copy(p);group.userData.index=i;
  if(i===0){for(let j=0;j<3;j++){const unit=mesh(new THREE.BoxGeometry(.85,.25,.65),dark);unit.position.y=.15+j*.32;group.add(unit);const slit=mesh(new THREE.BoxGeometry(.55,.035,.025),mint);slit.position.set(0,.15+j*.32,.34);group.add(slit)}}
  else if(i===1){const screen=mesh(new THREE.BoxGeometry(.95,.65,.14),dark);screen.position.y=.4;group.add(screen);const display=mesh(new THREE.BoxGeometry(.78,.48,.025),mint);display.position.set(0,.4,.085);group.add(display);const stand=mesh(new THREE.BoxGeometry(.12,.35,.12),dark);stand.position.y=-.05;group.add(stand);const base=mesh(new THREE.BoxGeometry(.62,.06,.4),dark);base.position.y=-.22;group.add(base)}
  else if(i===3){const certificate=mesh(new THREE.OctahedronGeometry(.48),purple);certificate.position.y=.4;group.add(certificate)}
  else{const head=mesh(new THREE.SphereGeometry(.18,16,12),i===2?purple:mint);head.position.y=.65;group.add(head);const body=mesh(new THREE.CylinderGeometry(.16,.32,.45,16),dark);body.position.y=.25;group.add(body)}
  const plinth=mesh(new THREE.CylinderGeometry(.7,.72,.1,32),dark);plinth.position.y=-.36;group.add(plinth);const ring=mesh(new THREE.TorusGeometry(.72,.013,5,48),i===3?purple:mint);ring.rotation.x=-Math.PI/2;ring.position.y=-.29;group.add(ring);world.add(group);return group;
 });
 const paths=[[4,2],[2,1],[1,0],[0,3],[4,0],[2,3]];const pulses:THREE.Mesh[]=[];
 paths.forEach(([a,b])=>{const geometry=new THREE.BufferGeometry().setFromPoints([positions[a],positions[b]]);geometries.push(geometry);const material=new THREE.LineBasicMaterial({color:0x579783,transparent:true,opacity:.48});materials.push(material);world.add(new THREE.Line(geometry,material));const pulse=mesh(new THREE.SphereGeometry(.035,8,6),mint);world.add(pulse);pulses.push(pulse)});
 const grid=new THREE.GridHelper(12,24,0x31554a,0x17342f);grid.position.y=-.65;world.add(grid);
 let selected=0,hover=-1,visible=true,disposed=false,raf=0,last=0,elapsed=0;const pointer=new THREE.Vector2(10,10),raycaster=new THREE.Raycaster();let aimX=0,aimY=0;
 const label=host.querySelector<HTMLElement>('[data-scene-label]')!,buttons=Array.from(host.querySelectorAll<HTMLButtonElement>('[data-scene-node]'));
 const updateLabel=(index:number)=>{label.textContent=buttons[index].dataset.label!};const select=(e:Event)=>{selected=Number((e.currentTarget as HTMLElement).dataset.sceneNode);updateLabel(selected)};buttons.forEach(b=>b.addEventListener('click',select));
 const move=(e:PointerEvent)=>{const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);aimX=pointer.x*.2;aimY=pointer.y*.08};const leave=()=>{pointer.set(10,10);hover=-1;aimX=aimY=0;updateLabel(selected)};stage.addEventListener('pointermove',move);stage.addEventListener('pointerleave',leave);
 const draw=(now:number)=>{if(disposed||!visible||document.hidden){raf=0;return}const dt=Math.min((now-last)/1000,.05);last=now;elapsed+=dt;world.rotation.y+=(aimX-world.rotation.y)*.05;world.rotation.x+=(aimY-world.rotation.x)*.05;nodes.forEach((node,i)=>{node.position.y=positions[i].y+Math.sin(elapsed*.65+i)*.045;const target=i===(hover>=0?hover:selected)?1.09:1;node.scale.lerp(new THREE.Vector3(target,target,target),.08)});pulses.forEach((p,i)=>{const [a,b]=paths[i];p.position.lerpVectors(positions[a],positions[b],(elapsed*.13+i*.17)%1)});raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(nodes,true)[0];if(hit){let obj:THREE.Object3D=hit.object;while(obj.parent&&obj.userData.index===undefined)obj=obj.parent;const index=obj.userData.index;if(index!==undefined&&hover!==index){hover=index;updateLabel(index)}}else if(hover!==-1){hover=-1;updateLabel(selected)}renderer.render(scene,camera);raf=requestAnimationFrame(draw)};
 const start=()=>{if(!raf&&!disposed&&visible&&!document.hidden){last=performance.now();raf=requestAnimationFrame(draw)}};
 const resize=()=>{const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.z=w<500?12:9;camera.updateProjectionMatrix();if(!raf)renderer.render(scene,camera)};const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(stage);resize();
 const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)start();else{cancelAnimationFrame(raf);raf=0}});intersection.observe(host);const visibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else start()};document.addEventListener('visibilitychange',visibility);
 const lost=(e:Event)=>{e.preventDefault();host.classList.remove('webgl-ready');status.textContent='Simplified topology';dispose()};canvas.addEventListener('webglcontextlost',lost);
 function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);resizeObserver.disconnect();intersection.disconnect();document.removeEventListener('visibilitychange',visibility);stage.removeEventListener('pointermove',move);stage.removeEventListener('pointerleave',leave);canvas.removeEventListener('webglcontextlost',lost);buttons.forEach(b=>b.removeEventListener('click',select));geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());grid.geometry.dispose();(Array.isArray(grid.material)?grid.material:[grid.material]).forEach(m=>m.dispose());renderer.dispose();host.classList.remove('webgl-ready');status.textContent='Topology preview'}
 host.classList.add('webgl-ready');status.textContent='WebGL · interactive';start();return dispose;
}
