import { getProgress, review, toggle, renderProgress } from './progress';
const root=document.querySelector<HTMLElement>('[data-question-workspace]');
if(root){
 const cards=Array.from(root.querySelectorAll<HTMLElement>('[data-question]'));
 let filter='all',mock=false,sequence:HTMLElement[]=[],position=0;
 const count=root.querySelector<HTMLElement>('[data-visible-count]')!,empty=root.querySelector<HTMLElement>('[data-empty-questions]')!,mockBar=root.querySelector<HTMLElement>('[data-mock-bar]')!;
 const visibleCards=()=>cards.filter(c=>filter==='all'||getProgress()[filter as 'favorites'|'difficult'].includes(c.dataset.question!));
 const update=()=>{if(mock)return;const shown=visibleCards();cards.forEach(c=>c.hidden=!shown.includes(c));count.textContent=`${shown.length} questions`;empty.hidden=shown.length>0};
 cards.forEach(card=>{card.querySelector<HTMLDetailsElement>('.answer-reveal')!.addEventListener('toggle',e=>{if((e.target as HTMLDetailsElement).open)review(card.dataset.question!)});card.querySelectorAll<HTMLButtonElement>('[data-mark]').forEach(b=>b.addEventListener('click',()=>{toggle(card.dataset.question!,b.dataset.mark as 'learned'|'difficult'|'favorites');update()}))});
 root.querySelectorAll<HTMLButtonElement>('[data-question-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.questionFilter!;root.querySelectorAll('[data-question-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});update()}));
 root.querySelector('[data-random-question]')?.addEventListener('click',()=>{const available=visibleCards();if(!available.length)return;const card=available[Math.floor(Math.random()*available.length)];card.querySelector<HTMLDetailsElement>('.answer-reveal')!.open=false;card.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});card.tabIndex=-1;card.focus({preventScroll:true})});
 const mockLabel=root.querySelector<HTMLElement>('[data-mock-label]')!,next=root.querySelector<HTMLButtonElement>('[data-mock-next]')!;
 const showMock=()=>{cards.forEach(c=>c.hidden=c!==sequence[position]);sequence[position].querySelector<HTMLDetailsElement>('.answer-reveal')!.open=false;mockLabel.textContent=`SELF PRACTICE / ${position+1} OF ${sequence.length}`;next.textContent=position===sequence.length-1?'Finish session':'Next question →'};
 const finish=()=>{mock=false;mockBar.hidden=true;root.querySelectorAll<HTMLButtonElement>('[data-question-filter], [data-random-question], [data-mock-start]').forEach(b=>b.disabled=false);update();root.querySelector<HTMLElement>('[data-session-message]')!.textContent='Session ended. Only answers opened were recorded as reviewed.'};
 root.querySelector('[data-mock-start]')?.addEventListener('click',()=>{sequence=[...visibleCards()];if(!sequence.length)return;for(let i=sequence.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[sequence[i],sequence[j]]=[sequence[j],sequence[i]]}sequence=sequence.slice(0,5);position=0;mock=true;mockBar.hidden=false;root.querySelectorAll<HTMLButtonElement>('[data-question-filter], [data-random-question], [data-mock-start]').forEach(b=>b.disabled=true);root.querySelector<HTMLElement>('[data-session-message]')!.textContent='Answer aloud, then reveal and assess your response. This mode does not grade you.';showMock()});
 next.addEventListener('click',()=>{if(position<sequence.length-1){position++;showMock()}else finish()});root.querySelector('[data-mock-exit]')?.addEventListener('click',finish);window.addEventListener('hexfield:progress',update);renderProgress();update();
}
